Colorize test PASS/FAIL indicators iff stdout is a tty.

diff --git a/tests/test-rem b/tests/test-rem
--- a/tests/test-rem
+++ b/tests/test-rem
@@ -34,6 +34,18 @@ CMP="../tests/test.cmp"
 TZ=Universal
 export TZ
 
+# Colorize output iff stdout is a tty
+stty <&1 > /dev/null 2>&1
+if test $? = 0; then
+    RED="[31m"
+    GRN="[32m"
+    NRM="[0m"
+else
+    RED=""
+    GRN=""
+    NRM=""
+fi
+
 # See if our version of sleep supports fractional sleeps
 sleep 0.2 > /dev/null 2>&1
 if test $? = 0 ; then
@@ -869,10 +881,10 @@ EOF
 (echo 'INCLUDECMD cat'; sleep $DELAY; echo 'set a 1/0') | $REMIND - 2025-10-01 >> $OUT 2>&1
 cmp -s $OUT $CMP
 if [ "$?" = "0" ]; then
-   echo "Remind:  Acceptance tests PASSED"
+   echo "Remind:  Acceptance tests ${GRN}PASSED${NRM}"
    exit 0
 else
-   echo "Remind:  Acceptance tests FAILED"
+   echo "Remind:  Acceptance tests ${RED}FAILED${NRM}"
    echo ""
    echo "Examine the file test.out to see where it differs from the"
    echo "reference file test.cmp.  Here are the first 200 lines of"
diff --git a/tests/test-timezone-support b/tests/test-timezone-support
--- a/tests/test-timezone-support
+++ b/tests/test-timezone-support
@@ -15,6 +15,18 @@ if test `id -u` = 0 ; then
     exit 1
 fi
 
+# Colorize output iff stdout is a tty
+stty <&1 > /dev/null 2>&1
+if test $? = 0; then
+    RED="[31m"
+    GRN="[32m"
+    NRM="[0m"
+else
+    RED=""
+    GRN=""
+    NRM=""
+fi
+
 # We alias "remind" here so that we don't inadvertently add code that
 # runs the system-installed verion of Remind rather than
 # ../src/remind.  This trick was suggested by Jochen Sprickerhof
@@ -180,10 +192,10 @@ EOF
 
 cmp -s $OUT $CMP
 if [ "$?" = "0" ] ; then
-    echo "Remind:   Time zone tests PASSED"
+    echo "Remind:   Time zone tests ${GRN}PASSED${NRM}"
     exit 0
 else
-    echo "Remind:   Time zone tests FAILED"
+    echo "Remind:   Time zone tests ${RED}FAILED${NRM}"
     echo "Examine the file tz.out to see where it differs from the"
     echo "reference file tz.cmp.  Here are the first 200 lines of"
     echo "diff -u tz.out tz.cmp"
